version: 2
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(\.\w+)?$/

      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/

      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

      - release:
          requires:
            - hold
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: circleci/python:3

    steps:
      - checkout

      - run:
          name: lint
          command: |
            sudo pip install flake8
            flake8 prepkit tests

      - run:
          name: build
          command: |
            if [[ $CIRCLE_TAG =~ ^v[0-9]+\..+$ ]]; then
              echo $CIRCLE_TAG | sed 's/^v//' > VERSION
            fi
            python setup.py sdist

      - persist_to_workspace:
          root: dist
          paths: '*.tar.gz'

      - persist_to_workspace:
          root: tests
          paths: '*'

  test:
    docker:
      - image: circleci/python:3

    steps:
      - attach_workspace:
          at: dist

      - run:
          name: install
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install pytest
            pip install dist/*.tar.gz

      - attach_workspace:
          at: tests

      - run:
          name: test
          command: |
            source venv/bin/activate
            pytest tests

  release:
    docker:
      - image: circleci/python:3

    steps:
      - attach_workspace:
          at: dist

      - deploy:
          name: release
          command: |
            sudo pip install twine
            twine upload dist/*.tar.gz
