version: 2
workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - dist:
          requires:
            - test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(\.\w+)?$/
            branches:
              ignore: /.*/

      - hold:
          type: approval
          requires:
            - dist
          filters:
            tags:
              only: /.*/

      - release:
          requires:
            - hold
          filters:
            tags:
              only: /.*/

jobs:
  test:
    docker:
      - image: circleci/python:3.6.2

    steps:
      - checkout

      - restore_cache:
          key: requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements/test.txt" }}

      - run:
          name: setup venv and pip install
          command: |
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt -r requirements/test.txt

      - save_cache:
          key: requirements-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements/test.txt" }}
          paths:
            - .venv

      - run:
          name: lint
          command: |
            source .venv/bin/activate
            python -m flake8 prepkit tests

      - run:
          name: test
          command: |
            source .venv/bin/activate
            pytest tests

  dist:
    docker:
      - image: circleci/python:3.6.2

    steps:
      - checkout

      - run:
          name: overwrite version
          command: echo $CIRCLE_TAG | sed 's/^v//' > VERSION

      - run:
          name: sdist
          command: python setup.py sdist

      - persist_to_workspace:
          root: dist
          paths: '*.tar.gz'

  release:
    docker:
      - image: circleci/python:3.6.2

    steps:
      - attach_workspace:
          at: dist

      - run:
          name: pip install
          command: sudo pip install twine

      - run:
          name: upload to PyPI
          command: twine upload dist/*
